export const SOURCE_META = {
  seed: {
    label: 'Demo Seed',
    tone: 'neutral',
    description: 'Preloaded sample data for exploration.'
  },
  imported: {
    label: 'Imported CSV',
    tone: 'live',
    description: 'Loaded from a local campaign performance file.'
  },
  live: {
    label: 'Live API',
    tone: 'live',
    description: 'Synced from a configured external API.'
  },
  simulated: {
    label: 'Simulated API',
    tone: 'warning',
    description: 'Generated because no live API credentials were available.'
  },
  inferred: {
    label: 'Inferred',
    tone: 'warning',
    description: 'Calculated from available campaign totals.'
  },
  ai: {
    label: 'AI Draft',
    tone: 'ai',
    description: 'Generated by AI from the visible campaign context.'
  }
};

export function getCampaignSourceMeta(campaign) {
  return SOURCE_META[campaign?.sourceType] || SOURCE_META.seed;
}
